spring.application.name=demo-rest
server.port=8088
# DGS GraphQL
dgs.graphql.path=/graphql
dgs.graphql.schema-locations=classpath*:graphql/**/*.graphql
dgs.graphql.graphiql.enabled=true
dgs.graphql.graphiql.path=/graphiql
dgs.graphql.introspection.enabled=true