spring:
  application:
    name: grpc-enrichment-client

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000    # ?????? ????????? ??????? ????? 2 ???
          max-attempts: 3           # ???????? 3 ???????
          multiplier: 2.0           # ?????? ????????? x2 (2? ? 4? ? 8?)

# HTTP-???? ??? Spring Boot (actuator, health)
# ?? ??????????? ? demo-rest (8080), audit-service (8081), analytics-server (8083)
server:
  port: 8082

# gRPC-??????
# ????? gRPC-??????? (grpc-analytics-server)
grpc:
  client:
    analytics-server:
      host: localhost
      port: 9090

# Actuator ? ???????? ???????? ???????
management:
  endpoints:
    web:
      exposure:
        include: health,info

